FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir \
      langgraph-cli python-dotenv

COPY langgraph.json .
COPY .env .

EXPOSE 8001

CMD ["langgraph", "serve", "--config", "./langgraph.json", "--host", "0.0.0.0", "--port", "8001"]
