services:
  graph:
    build:
      context: ../backend
      dockerfile: Dockerfile.graph
    ports:
      - "8001:8001"         # Expose port 8001
    env_file:
      - ../backend/.env     # Load environment vars

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"         # Expose port 8000
    depends_on:
      - graph
    env_file:
      - ../backend/.env     # Load environment vars


  frontend:
    platform: linux/amd64   # Cross-build for linux/amd64
    build:
      context: ../frontend  # Build frontend Docker image
    ports:
      - "3000:3000"         # Expose port 3000
    depends_on:
      - backend
