services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"         # Expose port 8000
    depends_on: []
    env_file:
      - ../backend/.env     # Load environment vars

  frontend:
    platform: linux/amd64   # Cross-build for linux/amd64
    build:
      context: ../frontend  # Build frontend Docker image
    ports:
      - "3000:3000"         # Expose port 3000
    depends_on:
      - backend
