services:
  graph:
    image: langgraph-server:local
    volumes:
      - ../backend/langgraph.json:/app/langgraph.json:ro
    command: >
      uvicorn -m langgraph_server.main:app
      --reload --host 0.0.0.0 --port 8001
      --config /app/langgraph.json
    ports:
      - "8001:8001"         # Expose port 8001
    env_file:
      - ../backend/.env     # Load environment vars

  backend:
    build: ../backend       # Build backend Docker image
    ports:
      - "8000:8000"         # Expose port 8000
    depends_on:
      - graph
    env_file:
      - ../backend/.env     # Load environment vars


  frontend:
    build:
      context: ../frontend  # Build frontend Docker image
      platform: linux/amd64 # Cross-build for linux/amd64
    ports:
      - "3000:3000"         # Expose port 3000
    depends_on:
      - backend
